DROP TABLE IF EXISTS public.order_type_aliases;

CREATE TABLE ORDER_TYPE_ALIASES (
    order_type char(1) NOT NULL,
    tbl_num int NOT NULL,
    tbl_name varchar(20) not null,
    floor_id int,
    picture varchar(50),
    position_x int,
    position_y int);

ALTER TABLE ORDER_TYPE_ALIASES ADD CONSTRAINT PK_ORDER_TYPE_ALIASES PRIMARY KEY (order_type, tbl_num);

ALTER TABLE public.order_type_aliases ADD CONSTRAINT fk_order_type_aliases_order_type FOREIGN KEY (order_type) 
    REFERENCES public.order_type (order_type) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE UNIQUE INDEX idx_order_type_aliases_order_type_nm ON order_type_aliases(order_type, tbl_name);

GRANT SELECT, UPDATE, INSERT, DELETE ON order_type_aliases TO public;


DROP TABLE IF EXISTS public.floor;

CREATE TABLE floor (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ) PRIMARY KEY,
    name varchar(100) not null
);

insert into floor (id, name) values (1,'Gnd Floor');
insert into floor (id, name) values (2,'2nd Floor');

CREATE UNIQUE INDEX idx_floor_floor_nm ON floor(name);

GRANT SELECT, UPDATE, INSERT, DELETE ON floor TO public;


DROP TABLE IF EXISTS public.table_picture;

CREATE TABLE table_picture (
    id integer NOT NULL PRIMARY KEY,
    filename varchar(100) not null
);

GRANT SELECT, UPDATE, INSERT, DELETE ON table_picture TO public;

insert into table_picture (id, filename) values (1, 'round2.png');
insert into table_picture (id, filename) values (2, 'round2_2.png');
insert into table_picture (id, filename) values (3, 'round4.png');
insert into table_picture (id, filename) values (4, 'round6.png');
insert into table_picture (id, filename) values (5, 'round8.png');
insert into table_picture (id, filename) values (6, 'square2.png');
insert into table_picture (id, filename) values (7, 'square2_2.png');
insert into table_picture (id, filename) values (8, 'square4.png');
insert into table_picture (id, filename) values (9, 'square4_2.png');
insert into table_picture (id, filename) values (10, 'square6.png');
insert into table_picture (id, filename) values (11, 'square6_2.png');
insert into table_picture (id, filename) values (12, 'square8.png');
insert into table_picture (id, filename) values (13, 'square8_2.png');



alter table food_delivery_app add column table_count int not null default 0;

