DROP TABLE IF EXISTS public.food_station;

CREATE TABLE FOOD_STATION (
    station_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ) PRIMARY KEY,
    station_code VARCHAR(50) NOT NULL,
    station_nm VARCHAR(100) NOT NULL
);

CREATE UNIQUE INDEX idx_food_station_food_station_nm ON food_station(station_nm);
CREATE UNIQUE INDEX idx_food_station_food_station_code ON food_station(station_code);

GRANT SELECT, UPDATE, INSERT, DELETE ON food_station TO public;

