 DROP TABLE IF EXISTS public.company_branch;

CREATE TABLE IF NOT EXISTS public.company_branch
(
    cmpy_nm character varying(255) COLLATE pg_catalog."default" NOT NULL,
    operated_by character varying(255) COLLATE pg_catalog."default",
    tin_no character varying(255) COLLATE pg_catalog."default",
    address1 character varying(255) COLLATE pg_catalog."default",
    address2 character varying(255) COLLATE pg_catalog."default",
    roller_txt character varying(255) COLLATE pg_catalog."default",
    delivery_charge_flag character(1) COLLATE pg_catalog."default",
    branch_manager character varying(255) COLLATE pg_catalog."default",
    branch_tel_no character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    logo_filename character varying(255) COLLATE pg_catalog."default",
    dinein_count integer,
    pickup_count integer,
    dlvry_count integer,
    send_to_kitchen character varying(255) COLLATE pg_catalog."default",
    track_invty_flag character varying(255) COLLATE pg_catalog."default",
    reset_key character varying(255) COLLATE pg_catalog."default",
    reset_counter character varying(255) COLLATE pg_catalog."default",
    reset_date character varying(255) COLLATE pg_catalog."default",
    last_print_date timestamp without time zone,
    last_slip_no integer,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 )
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.company_branch
    OWNER to postgres;

INSERT INTO public.company_branch(
	cmpy_nm, operated_by, tin_no, address1, address2, track_invty_flag, reset_key, reset_counter, reset_date, 
	last_print_date, last_slip_no, roller_txt, 
	delivery_charge_flag, branch_manager, branch_tel_no, email, dinein_count, send_to_kitchen, id, dlvry_count, pickup_count,logo_filename)
	VALUES ('Chicks ni Otit', 'Otit company', '888-888-888', 
	'4W3Q+738, Mahogany Ave', 'Tagaytay, Cavite', 
	'Y', '3333', 1, '(#,(#&$!&$!&"', 
	null, 1, 'HALIKA NA, KAKAIN NA! Sa Chicks Ni Otit', 
	'N', 'Ralph Columna ', '0922 270 1782', 'test@gmail.com', 20, 'Y', 1, 50, 50,null);

DROP PROCEDURE IF EXISTS public.update_company;

CREATE OR REPLACE PROCEDURE public.update_company(
	IN p_id int,
  IN p_cmpy_nm character varying, 
  IN p_operated_by character varying, 
  IN p_tin_no character varying, 
  IN p_address1 character varying,  
  IN p_address2 character varying,  
  IN p_roller_txt character varying, 
  IN p_branch_manager character varying, 
  IN p_branch_tel_no character varying, 
  IN p_email character varying, 
  IN p_logo_filename character varying, 
  IN p_dinein_count int default 0,
  IN p_pickup_count int default 0,
  IN p_dlvry_count int default 0,
  IN p_send_to_kitchen character varying default 'Y', 
  IN p_track_invty_flag character varying default 'Y')
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
  UPDATE company_branch 
  SET cmpy_nm = p_cmpy_nm, 
      operated_by = p_operated_by, 
      tin_no = p_tin_no, 
      address1 = p_address1,  
      address2 = p_address2, 
      roller_txt = p_roller_txt, 
      branch_manager = p_branch_manager, 
      branch_tel_no = p_branch_tel_no, 
      email = p_email, 
      logo_filename = NULLIF(p_logo_filename, ''), 
      dinein_count = p_dinein_count,
      pickup_count = p_pickup_count,
      dlvry_count = p_dlvry_count,
      send_to_kitchen = p_send_to_kitchen, 
      track_invty_flag = p_track_invty_flag
  WHERE id = p_id;
END;
$BODY$;
ALTER PROCEDURE public.update_company(int, 
character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, 
int, int, int, character varying, character varying)
    OWNER TO postgres;

DROP TABLE IF EXISTS public.food_station;

CREATE TABLE FOOD_STATION (
    station_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ) PRIMARY KEY,
    station_code VARCHAR(50) NOT NULL,
    station_nm VARCHAR(100) NOT NULL
);

CREATE UNIQUE INDEX idx_food_station_food_station_nm ON food_station(station_nm);
CREATE UNIQUE INDEX idx_food_station_food_station_code ON food_station(station_code);

GRANT SELECT, UPDATE, INSERT, DELETE ON food_station TO public;

