package com.smartdata.resto_console.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.query.Procedure;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import com.smartdata.resto_console.model.DeliveryApp;
import java.util.List;
import org.springframework.data.jpa.repository.Query;

@Repository
public interface DeliveryAppRepository extends JpaRepository<DeliveryApp, Integer> {

    // declare stored procedure mapping here for use in service
    @Procedure(name = "addDeliveryApp")
    void addDeliveryApp(@Param("p_app_nm") String app_nm, @Param("p_order_type") String order_type, @Param("p_active_flag") String active_flag, 
        @Param("p_table_count") Integer table_count, @Param("p_pic_filename") String pic_filename);

    @Procedure(name = "updateDeliveryApp")
    void updateDeliveryApp(@Param("p_app_id") Integer id, @Param("p_app_nm") String app_nm, @Param("p_order_type") String order_type, @Param("p_active_flag") String active_flag, 
        @Param("p_table_count") Integer table_count, @Param("p_pic_filename") String pic_filename);

    @Procedure(name = "deleteDeliveryApp")
    void deleteDeliveryApp(@Param("p_app_id") Integer id);

    // auto generated by JPA, no need for code
    List<DeliveryApp> findByAppNmContainingIgnoreCaseOrderById(String appNm);

    // auto generated by JPA, no need for code
    List<DeliveryApp> findAllByOrderById();        
}
