package com.smartdata.resto_console.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.query.Procedure;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import com.smartdata.resto_console.model.EmployeeStatus;
import java.util.List;
import org.springframework.data.jpa.repository.Query;

@Repository
public interface EmployeeStatusRepository extends JpaRepository<EmployeeStatus, Integer> {

    // Sort all by unit_code
    // auto generated by JPA, no need for code
    List<EmployeeStatus> findAllByOrderByEmpStatusId();    
}
