package com.smartdata.resto_console.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.query.Procedure;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import com.smartdata.resto_console.model.Floor;
import java.util.List;
import org.springframework.data.jpa.repository.Query;

@Repository
public interface FloorRepository extends JpaRepository<Floor, Integer> {

    // declare stored procedure mapping here for use in service
    @Procedure(name = "addFloor")
    void addFloor(@Param("p_name") String name);

    @Procedure(name = "updateFloor")
    void updateFloor(@Param("p_id") Integer id, @Param("p_name") String name);

    @Procedure(name = "deleteFloor")
    void deleteFloor(@Param("p_id") Integer id);

    @Query("SELECT f FROM Floor f WHERE LOWER(f.name) LIKE LOWER(concat('%', :searchTerm, '%')) ORDER BY f.name")
    List<Floor> findByNameContainingIgnoreCaseOrderByName(@Param("searchTerm") String searchTerm);

    // Sort all by unit_code
    // auto generated by JPA, no need for code
    List<Floor> findAllByOrderByName();    
}
