package com.smartdata.resto_console.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.query.Procedure;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import com.smartdata.resto_console.model.ItemGroup;
import java.util.List;
import org.springframework.data.jpa.repository.Query;

@Repository
public interface ItemGroupRepository extends JpaRepository<ItemGroup, Integer> {

    // declare stored procedure mapping here for use in service
    @Procedure(name = "addItemGroup")
    void addItemGroup(@Param("p_item_grp_desc") String item_grp_desc);

    @Procedure(name = "updateItemGroup")
    void updateItemGroup(@Param("p_item_grp_id") Integer item_grp_id, @Param("p_item_grp_desc") String item_grp_desc);

    @Procedure(name = "deleteItemGroup")
    void deleteItemGroup(@Param("p_item_grp_id") Integer item_grp_id);

    @Query("SELECT f FROM ItemGroup f WHERE LOWER(f.itemGrpDesc) LIKE LOWER(concat('%', :searchTerm, '%')) ORDER BY f.itemGrpDesc")
    List<ItemGroup> findByItemGrpDescContainingIgnoreCaseOrderByItemGrpDesc(@Param("searchTerm") String searchTerm);

    // auto generated by JPA, no need for code,   if field name is more than 3 eg item_grp_desc  it will not work n need to use query. JPA only works with 2 like app_nm
    @Query("SELECT f FROM ItemGroup f ORDER BY f.itemGrpDesc")
    List<ItemGroup> findAllByOrderByItemGrpDesc();    

}