package com.smartdata.resto_console.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.query.Procedure;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import com.smartdata.resto_console.model.ItemTag;
import java.util.List;
import org.springframework.data.jpa.repository.Query;

@Repository
public interface ItemTagRepository extends JpaRepository<ItemTag, Integer> {

    // declare stored procedure mapping here for use in service
    @Procedure(name = "addItemTag")
    void addItemTag(@Param("p_item_tag_desc") String item_tag_desc);

    @Procedure(name = "updateItemTag")
    void updateItemTag(@Param("p_item_tag_id") Integer item_tag_id, @Param("p_item_tag_desc") String item_tag_desc);

    @Procedure(name = "deleteItemTag")
    void deleteItemTag(@Param("p_item_tag_id") Integer item_tag_id);

    @Query("SELECT f FROM ItemTag f WHERE LOWER(f.itemTagDesc) LIKE LOWER(concat('%', :searchTerm, '%')) ORDER BY f.itemTagDesc")
    List<ItemTag> findByNameContainingIgnoreCaseOrderByName(@Param("searchTerm") String searchTerm);

    // auto generated by JPA, no need for code
    @Query("SELECT f FROM ItemTag f ORDER BY f.itemTagDesc")
    List<ItemTag> findAllByOrderByItemTagDesc();    

}