package com.smartdata.resto_console.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.query.Procedure;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import com.smartdata.resto_console.model.PayMethod;
import java.util.List;
import org.springframework.data.jpa.repository.Query;

@Repository
public interface PayMethodRepository extends JpaRepository<PayMethod, Integer> {

    // declare stored procedure mapping here for use in service
    @Procedure(name = "addPayMethod")
    void addPayMethod(
        @Param("p_pay_mtd_desc") String pay_mtd_desc, 
        @Param("p_parent_pay_mtd_id") Integer parent_pay_mtd_id, 
        @Param("p_is_category") String is_category, 
        @Param("p_picture_src") String picture_src, 
        @Param("p_need_ref") String need_ref, 
        @Param("p_need_expdt") String need_expdt, 
        @Param("p_short_nm") String short_nm, 
        @Param("p_active_flag") String active_flag, 
        @Param("p_bank_charges") Double bank_charges,
        @Param("p_sm_pay_type") Integer sm_pay_type);

    @Procedure(name = "updatePayMethod")
    void updatePayMethod(@Param("p_pay_mtd_id") Integer id, 
        @Param("p_pay_mtd_desc") String pay_mtd_desc, 
        @Param("p_parent_pay_mtd_id") Integer parent_pay_mtd_id, 
        @Param("p_is_category") String is_category, 
        @Param("p_picture_src") String picture_src, 
        @Param("p_need_ref") String need_ref, 
        @Param("p_need_expdt") String need_expdt, 
        @Param("p_short_nm") String short_nm, 
        @Param("p_active_flag") String active_flag, 
        @Param("p_bank_charges") Double bank_charges,
        @Param("p_sm_pay_type") Integer sm_pay_type);

    @Procedure(name = "deletePayMethod")
    void deletePayMethod(@Param("p_pay_mtd_id") Integer id);

    // auto generated by JPA, no need for code
    List<PayMethod> findByPayMtdDescContainingIgnoreCaseOrderById(String payMtdDesc);

    // auto generated by JPA, no need for code
    List<PayMethod> findByIsCategoryContainingIgnoreCaseOrderById(String isCategory);

    // auto generated by JPA, no need for code
    List<PayMethod> findAllByOrderById();        
}
