package com.smartdata.resto_console.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.query.Procedure;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import com.smartdata.resto_console.model.StorageLocation;

import java.util.List;
import org.springframework.data.jpa.repository.Query;

@Repository
public interface StorageLocationRepository extends JpaRepository<StorageLocation, Integer> {

    // declare stored procedure mapping here for use in service
    @Procedure(name = "addStorageLocation")
    void addStorageLocation(@Param("p_location_nm") String location_nm);

    @Procedure(name = "updateStorageLocation")
    void updateStorageLocation(@Param("p_location_id") Integer location_id, @Param("p_location_nm") String location_nm);

    @Procedure(name = "deleteStorageLocation")
    void deleteStorageLocation(@Param("p_location_id") Integer location_id);

    @Query("SELECT f FROM StorageLocation f WHERE LOWER(f.locationNm) LIKE LOWER(concat('%', :searchTerm, '%')) ORDER BY f.locationNm")
    List<StorageLocation> findByNameContainingIgnoreCaseOrderByName(@Param("searchTerm") String searchTerm);

    // Sort all by location_nm
    // auto generated by JPA, no need for code
    List<StorageLocation> findAllByOrderByLocationNm();    
}
